"""Bill Modal Update1

Revision ID: 3c3bb0936848
Revises: 4064efd8d09b
Create Date: 2026-04-15 00:47:04.964170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3bb0936848'
down_revision = '4064efd8d09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('amount_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('bills_patient_Id_fkey'), type_='foreignkey')
        batch_op.drop_column('bill_type')
        batch_op.drop_column('status')
        batch_op.drop_column('description')

    with op.batch_alter_table('treatment_catalogue', schema=None) as batch_op:
        batch_op.drop_column('dept_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_catalogue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bill_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('bills_patient_Id_fkey'), 'patients', ['patient_Id'], ['patient_Id'])
        batch_op.alter_column('balance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('amount_paid',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
