"""Bill Modal Update

Revision ID: 3c4dc1f25b21
Revises: e31cd5af5304
Create Date: 2026-04-15 00:19:40.677378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c4dc1f25b21'
down_revision = 'e31cd5af5304'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('bills') as batch_op:

        batch_op.add_column(
            sa.Column('record_Id', sa.Integer(), nullable=True)
        )

        batch_op.add_column(
            sa.Column('appointment_Id', sa.Integer(), nullable=True)
        )

        batch_op.add_column(
            sa.Column('total_amount',
            sa.Numeric(10,2), nullable=True)
        )

        batch_op.add_column(
            sa.Column('amount_paid',
            sa.Numeric(10,2), nullable=True)
        )

        batch_op.add_column(
            sa.Column('balance',
            sa.Numeric(10,2), nullable=True)
        )

        batch_op.add_column(
            sa.Column('bill_status',
            sa.String(20), nullable=True)
        )

        batch_op.add_column(
            sa.Column('notes',
            sa.String(255), nullable=True)
        )

        batch_op.add_column(
            sa.Column('created_by',
            sa.Integer(), nullable=True)
        )

        batch_op.add_column(
            sa.Column('created_at',
            sa.DateTime(), nullable=True)
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_catalogue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_bill_id_fkey'), 'bills', ['bill_id'], ['bill_id'])

    op.create_table('bills',
    sa.Column('bill_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_Id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount_paid', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bill_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_Id'], ['patients.patient_Id'], name=op.f('bills_patient_Id_fkey')),
    sa.PrimaryKeyConstraint('bill_id', name=op.f('bills_pkey'))
    )
    op.drop_table('bill')
    # ### end Alembic commands ###
