"""Medical Record - added column opid

Revision ID: 7c68694993fd
Revises: 2191e7e4e084
Create Date: 2026-04-17 12:57:06.421980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c68694993fd'
down_revision = '2191e7e4e084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_Id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.drop_column('appointment_Id')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
