"""add relationships

Revision ID: 8c1572598420
Revises: feb62af0aee0
Create Date: 2026-04-13 17:19:41.351428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c1572598420'
down_revision = 'feb62af0aee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patients', ['patient_Id'], ['patient_Id'])
        batch_op.create_foreign_key(None, 'doctor', ['doct_Id'], ['doct_Id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['User_ID'])

    with op.batch_alter_table('bed', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ward', ['ward_No'], ['ward_No'])

    with op.batch_alter_table('bed_records', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'helpers', ['helper_Id'], ['helper_Id'])
        batch_op.create_foreign_key(None, 'bed', ['bed_No'], ['bed_No'])
        batch_op.create_foreign_key(None, 'nurse', ['nurse_Id'], ['nurse_Id'])
        batch_op.create_foreign_key(None, 'patients', ['patient_Id'], ['patient_Id'])

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patients', ['patient_Id'], ['patient_Id'])
        batch_op.drop_column('payment_link')
        batch_op.drop_column('amount')
        batch_op.drop_column('stripe_session_id')
        batch_op.drop_column('notes')
        batch_op.drop_column('paid_at')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['User_ID'], ['User_ID'])
        batch_op.create_foreign_key(None, 'department', ['dept_Id'], ['dept_Id'])
        batch_op.drop_column('available')
        batch_op.drop_column('qualification')
        batch_op.drop_column('consultation_fee')

    with op.batch_alter_table('helpers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['User_ID'], ['User_ID'])
        batch_op.create_foreign_key(None, 'department', ['dept_Id'], ['dept_Id'])

    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chief_complaint', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prescription', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('followup_required', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'doctor', ['doct_Id'], ['doct_Id'])
        batch_op.create_foreign_key(None, 'patients', ['patient_Id'], ['patient_Id'])

    with op.batch_alter_table('nurse', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['User_ID'], ['User_ID'])
        batch_op.create_foreign_key(None, 'department', ['dept_Id'], ['dept_Id'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['User_ID'], ['User_ID'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'bills', ['bill_id'], ['bill_id'])

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'department', ['dept_Id'], ['dept_Id'])

    with op.batch_alter_table('room_records', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'room', ['room_no'], ['room_No'])
        batch_op.create_foreign_key(None, 'helpers', ['helper_Id'], ['helper_Id'])
        batch_op.create_foreign_key(None, 'nurse', ['nurse_Id'], ['nurse_Id'])
        batch_op.create_foreign_key(None, 'patients', ['patient_Id'], ['patient_Id'])

    with op.batch_alter_table('staff_shifts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'helpers', ['helper_Id'], ['helper_Id'])
        batch_op.create_foreign_key(None, 'doctor', ['doct_Id'], ['doct_Id'])
        batch_op.create_foreign_key(None, 'nurse', ['nurse_Id'], ['nurse_Id'])

    with op.batch_alter_table('surgery_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'room', ['room_no'], ['room_No'])
        batch_op.create_foreign_key(None, 'nurse', ['nurse_Id'], ['nurse_Id'])
        batch_op.create_foreign_key(None, 'doctor', ['surgeon_Id'], ['doct_Id'])
        batch_op.create_foreign_key(None, 'helpers', ['helper_Id'], ['helper_Id'])
        batch_op.create_foreign_key(None, 'patients', ['patient_Id'], ['patient_Id'])

    with op.batch_alter_table('ward', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'department', ['dept_Id'], ['dept_Id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ward', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('surgery_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cost')
        batch_op.drop_column('status')

    with op.batch_alter_table('staff_shifts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('room_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('nurse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('followup_required')
        batch_op.drop_column('prescription')
        batch_op.drop_column('chief_complaint')

    with op.batch_alter_table('helpers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('qualification', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stripe_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bed_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bed', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
