"""Added leave and contact models

Revision ID: d9890b02457b
Revises: 7c68694993fd
Create Date: 2026-05-14 14:30:02.367282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9890b02457b'
down_revision = '7c68694993fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('doctor_leave',
    sa.Column('leave_id', sa.Integer(), nullable=False),
    sa.Column('doct_Id', sa.Integer(), nullable=True),
    sa.Column('leave_from', sa.Date(), nullable=True),
    sa.Column('leave_to', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doct_Id'], ['doctor.doct_Id'], ),
    sa.PrimaryKeyConstraint('leave_id')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_bills_patient'))
        batch_op.drop_constraint(batch_op.f('fk_bills_appt'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_bills_patient'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_bills_record'), type_='foreignkey')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payments_bill'))
        batch_op.drop_constraint(batch_op.f('fk_payments_bill'), type_='foreignkey')

    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_treatments_appt'))
        batch_op.drop_index(batch_op.f('idx_treatments_patient'))
        batch_op.drop_constraint(batch_op.f('fk_treatments_catalogue'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_treatments_appt'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_treatments_patient'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_treatments_record'), type_='foreignkey')
        batch_op.drop_column('treatment_catalogue_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_catalogue_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_treatments_record'), 'medical_record', ['record_id'], ['record_Id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_treatments_patient'), 'patients', ['patient_Id'], ['patient_Id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_treatments_appt'), 'appointment', ['appointment_Id'], ['appointment_Id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_treatments_catalogue'), 'treatment_catalogue', ['treatment_catalogue_id'], ['treatment_id'])
        batch_op.create_index(batch_op.f('idx_treatments_patient'), ['patient_Id'], unique=False)
        batch_op.create_index(batch_op.f('idx_treatments_appt'), ['appointment_Id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_payments_bill'), 'bills', ['bill_id'], ['bill_id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_payments_bill'), ['bill_id'], unique=False)

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_bills_record'), 'medical_record', ['record_Id'], ['record_Id'])
        batch_op.create_foreign_key(batch_op.f('fk_bills_patient'), 'patients', ['patient_Id'], ['patient_Id'])
        batch_op.create_foreign_key(batch_op.f('fk_bills_appt'), 'appointment', ['appointment_Id'], ['appointment_Id'])
        batch_op.create_index(batch_op.f('idx_bills_patient'), ['patient_Id'], unique=False)

    op.drop_table('doctor_leave')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
