"""Treatment Catalogue Update

Revision ID: e31cd5af5304
Revises: f09bce7fbe25
Create Date: 2026-04-14 22:03:38.433916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31cd5af5304'
down_revision = 'f09bce7fbe25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_catalogue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_Id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('default_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('treatment_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.create_foreign_key(None, 'department', ['dept_Id'], ['dept_Id'])
        batch_op.drop_column('description')
        batch_op.drop_column('cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_catalogue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('treatment_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('default_cost')
        batch_op.drop_column('category')
        batch_op.drop_column('dept_Id')

    # ### end Alembic commands ###
