"""fee + slots

Revision ID: f09bce7fbe25
Revises: 8c1572598420
Create Date: 2026-04-14 18:25:42.061770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09bce7fbe25'
down_revision = '8c1572598420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_slots',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('doct_Id', sa.Integer(), nullable=True),
    sa.Column('slot_time', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doct_Id'], ['doctor.doct_Id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('fee_master',
    sa.Column('fee_id', sa.Integer(), nullable=False),
    sa.Column('dept_Id', sa.Integer(), nullable=True),
    sa.Column('doct_Id', sa.Integer(), nullable=True),
    sa.Column('fee_type', sa.String(length=50), nullable=True),
    sa.Column('treatment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dept_Id'], ['department.dept_Id'], ),
    sa.ForeignKeyConstraint(['doct_Id'], ['doctor.doct_Id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment_catalogue.treatment_id'], ),
    sa.PrimaryKeyConstraint('fee_id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('consultation_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('consultation_fee')
        batch_op.drop_column('slot_time')

    op.drop_table('fee_master')
    op.drop_table('doctor_slots')
    # ### end Alembic commands ###
